gpu_id: 3
multi_gpus: False
num_workers: 16 #16
seed: 666
exp_name: 'expTGIF-QAFrameQA'

# #gpu_id: 1
# multi_gpus: False
# num_workers: 0
# seed: 666
# exp_name: 'expTGIF-QAFrameQA'

train:
  lr: 0.0001
  batch_size: 32 # (1024 -> 1.1 h per epoch) # 32 -> 36 h per epoch
  restore: True
  max_epochs: 2305
  word_dim: 300
  
  module_dim: 512
  glove: True
  k_max_frame_level: 16
  k_max_clip_level: 24
  spl_resolution: 1


val:
  flag: True

test:
  test_num: 0
  write_preds: False

dataset:
  name: 'tgif-qa'
  question_type: 'frameqa'
  data_dir: 'data/tgif-qa/frameqa' #Nothing in this folder
  #save_dir: 'results/gpt2_captions/'
  save_dir: 'results/results_vicreg/'